name: Node.js and TypeScript CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 17, 18, 19, 20, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install && npm install typescript@5.3.3 && npm install uglifyjs

      - name: Build TypeScript
        run: npm run build:release

      - name: Run build
        run: node lib/src/index.js
